- name: update all systems
  hosts: webservers, nfs, dbserver, lb
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark using yum
      yum:
        name: wireshark
        state: removed
      when: ansible_pkg_mgr == "yum"

    - name: delete wireshark using apt
      apt:
        name: wireshark
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes
      when: ansible_pkg_mgr == "apt"